# Generated by Django 6.1 on 2026-08-16 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rotation_period', models.CharField(max_length=50)),
                ('orbital_period', models.CharField(max_length=50)),
                ('diameter', models.CharField(max_length=50)),
                ('climate', models.CharField(max_length=50)),
                ('gravity', models.CharField(max_length=50)),
                ('terrain', models.CharField(max_length=50)),
                ('surface_water', models.CharField(max_length=50)),
                ('population', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('mass', models.CharField(max_length=100)),
                ('hair_color', models.CharField(max_length=50)),
                ('skin_color', models.CharField(max_length=50)),
                ('eye_color', models.CharField(max_length=50)),
                ('birth_year', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homeworld', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='api.planet')),
            ],
        ),
    ]
